<a href="https://colab.research.google.com/github/Meruja/PythonExercises/blob/main/numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [3]:
# Create a 1-dimensional NumPy array using np.array()
one_d = np.array([1, 2, 3, 4])

# Create a 2-dimensional NumPy array using np.array()
two_d = np.array([[2, 3], [4, 5], [6, 8]])

# Create a 3-dimensional Numpy array using np.array()
three_d =np.array([[[1, 2, 3], [1, 3, 4]], [[1, 2, 3], [1, 3, 4]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
one_d.shape,one_d.ndim , one_d.dtype, type(one_d)

((4,), 1, dtype('int64'), numpy.ndarray)

In [5]:
# Attributes of 2-dimensional array
two_d.shape,two_d.ndim , two_d.dtype, type(two_d)

((3, 2), 2, dtype('int64'), numpy.ndarray)

In [6]:
# Attributes of 3-dimensional array
three_d.shape, three_d.ndim , three_d.dtype, type(three_d)

((2, 2, 3), 3, dtype('int64'), numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

numbers =pd.DataFrame(two_d, index= ["shoe", "socks", "dress"], columns= ["boys", "girls"])
numbers

boys  girls
shoe      2      3
socks     4      5
dress     6      8

In [9]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [2]:
# Create an array within a range of 0 and 100 with step 3
a1 = np.arange(0, 100, 3)
a1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [3]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a2 = np.random.randint(0, 10, (7, 2))
a2

array([[8, 0],
       [7, 2],
       [8, 0],
       [3, 3],
       [6, 0],
       [6, 5],
       [5, 3]])

In [4]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a3 = np.random.random((3, 5))
a3

array([[0.58914732, 0.07887469, 0.15173281, 0.75189874, 0.96589914],
       [0.39766825, 0.71106472, 0.38035986, 0.66030078, 0.16596038],
       [0.54938863, 0.29341175, 0.12366945, 0.91177658, 0.89063871]])

In [5]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a4 = np.random.randint(0, 10, (4,6))
a4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [6]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a5 = np.random.randint(1, 10, (3, 7))

# Find the unique numbers in the array you just created
uni_num = np.unique(a5)
uni_num

array([1, 2, 3, 4, 5, 7, 9])

In [7]:
# Find the 0'th index of the latest array you created
uni_num[0]

1

In [9]:
# Get the first 2 rows of latest array you created
a5[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [10]:
# Get the first 2 values of the first 2 rows of the latest array
a5[:2, :2]

array([[9, 1],
       [5, 3]])

In [15]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a6 = np.random.randint(0, 10, (3, 5))
ones = np.ones((3,5))

In [16]:
# Add the two arrays together
a6 + ones

array([[1., 9., 7., 9., 8.],
       [1., 8., 8., 3., 1.],
       [8., 3., 3., 1., 5.]])

In [18]:
# Create another array of ones of shape (5, 3)
a7 = np.random.randint(0, 4, (5, 3))
a7

array([[3, 0, 2],
       [3, 3, 1],
       [2, 2, 0],
       [2, 0, 2],
       [1, 2, 0]])

In [19]:
# Try add the array of ones and the other most recent array together
ones + a7

ValueError: ignored

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)
a8 =ones.T
a8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# Subtract the new array of ones from the other most recent array
a7 - a8

array([[ 2., -1.,  1.],
       [ 2.,  2.,  0.],
       [ 1.,  1., -1.],
       [ 1., -1.,  1.],
       [ 0.,  1., -1.]])

In [27]:
# Multiply the ones array with the latest array
a7 * a8

array([[3., 0., 2.],
       [3., 3., 1.],
       [2., 2., 0.],
       [2., 0., 2.],
       [1., 2., 0.]])

In [28]:
# Take the latest array to the power of 2 using '**'
a7 **2

array([[9, 0, 4],
       [9, 9, 1],
       [4, 4, 0],
       [4, 0, 4],
       [1, 4, 0]])

In [29]:
# Do the same thing with np.square()
np.square(a7)

array([[9, 0, 4],
       [9, 9, 1],
       [4, 4, 0],
       [4, 0, 4],
       [1, 4, 0]])

In [31]:
# Find the mean of the latest array using np.mean()
np.mean(a7)

1.5333333333333334

In [32]:
# Find the maximum of the latest array using np.max()
np.max(a7)

3

In [33]:
# Find the minimum of the latest array using np.min()
np.min(a7)

0

In [34]:
# Find the standard deviation of the latest array
np.std(a7)

1.0873004286866728

In [35]:
# Find the variance of the latest array
np.var(a7)

1.1822222222222223

In [38]:
# Reshape the latest array to (3, 5, 1)
a7.reshape(3, 5, 1)

array([[[3],
        [0],
        [2],
        [3],
        [3]],

       [[1],
        [2],
        [2],
        [0],
        [2]],

       [[0],
        [2],
        [1],
        [2],
        [0]]])

In [39]:
# Transpose the latest array
a7.T

array([[3, 3, 2, 2, 1],
       [0, 3, 2, 0, 2],
       [2, 1, 0, 2, 0]])

What does the transpose do?

In [41]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
b1 = np.random.randint(0, 10, (3, 3))
b2 = np.random.randint(0, 10, (3,2))
b1, b2

(array([[3, 6, 2],
        [5, 1, 9],
        [8, 4, 5]]),
 array([[3, 9],
        [6, 8],
        [6, 0]]))

In [43]:
# Perform a dot product on the two newest arrays you created
np.dot(b1, b2)

array([[ 57,  75],
       [ 75,  53],
       [ 78, 104]])

In [44]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
c1 = np.random.randint(0, 10, (4, 3))
c2 = np.random.randint(0, 10, (4,3))
c1, c2

(array([[0, 8, 8],
        [3, 8, 2],
        [6, 5, 7],
        [8, 4, 0]]),
 array([[2, 9, 7],
        [5, 7, 8],
        [3, 0, 0],
        [9, 3, 6]]))

In [45]:
# Perform a dot product on the two newest arrays you created
np.dot(c1, c2)

ValueError: ignored

It doesn't work. How would you fix it?

In [46]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(c1.T, c2)

array([[105,  45,  72],
       [107, 140, 144],
       [ 47,  86,  72]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [48]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
c1 = np.random.randint(0, 10, (4, 3))
c2 = np.random.randint(0, 10, (4,3))

In [49]:
# Compare the two arrays with '>'
c1 > c2

array([[False,  True,  True],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [50]:
# Compare the two arrays with '>='
c1 >= c2

array([[False,  True,  True],
       [False,  True, False],
       [ True, False, False],
       [ True,  True, False]])

In [53]:
# Find which elements of the first array are greater than 7
c3 = c1 > 7
c1, c3

(array([[0, 5, 7],
        [4, 3, 1],
        [5, 5, 0],
        [8, 5, 2]]),
 array([[False, False, False],
        [False, False, False],
        [False, False, False],
        [ True, False, False]]))

In [54]:
# Which parts of each array are equal? (try using '==')
c1 == 7

array([[False, False,  True],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [55]:
# Sort one of the arrays you just created in ascending order
np.sort(c1)

array([[0, 5, 7],
       [1, 3, 4],
       [0, 5, 5],
       [2, 5, 8]])

In [56]:
# Sort the indexes of one of the arrays you just created
np.argsort(c1)

array([[0, 1, 2],
       [2, 1, 0],
       [2, 0, 1],
       [2, 1, 0]])

In [57]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(c1)

9

In [58]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(c1)

0

In [59]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(c1, axis=1)

array([2, 0, 0, 0])

In [60]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(c1, axis=0)

array([0, 1, 2])

In [61]:
# Create an array of normally distributed random numbers
np.random.randn(2, 3)

array([[ 0.62054822, -0.16093738, -0.3882644 ],
       [-0.88551237, -0.35674503,  0.5561218 ]])

In [63]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.